
import { StyleSheet, Dimensions } from 'react-native';

const {width} = Dimensions.get('window');
const styles = StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: '#F5F5F5',
    },
    container: {
      flex: 1,
    },
    upperContainer: {
      width: '100%',
      padding: 20,
      backgroundColor: '#111214',
      borderBottomLeftRadius: 30,
      borderBottomRightRadius: 30,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
    },
    topBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    rightContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 153, 0, 0.1)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: '#ff9900',
    },
    logoutText: {
      fontSize: 14,
      color: '#ff9900',
      fontWeight: '600',
      marginLeft: 4,
    },
    dateContainer: {
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      padding: 8,
      borderRadius: 15,
    },
    date: {
      fontSize: 16,
      color: '#ff9900',
      fontWeight: '500',
    },
    gymName: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#ff9900',
      textShadowColor: 'rgba(0, 0, 0, 0.2)',
      textShadowOffset: {width: 1, height: 1},
      textShadowRadius: 3,
    },
    dateContainer: {
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      padding: 8,
      borderRadius: 15,
    },
    date: {
      fontSize: 16,
      color: '#ff9900',
      fontWeight: '500',
    },
    avatarSection: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 10,
    },
    avatarWrapper: {
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    avatar: {
      width: 80,
      height: 80,
      borderRadius: 45,
      borderWidth: 3,
      borderColor: '#FFFFFF',
    },
    greetingContainer: {
      marginLeft: 20,
    },
    greeting: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#ff9900',
      marginBottom: 5,
    },
    motivation: {
      fontSize: 18,
      color: '#E0E0E0',
      fontWeight: '500',
    },
    lowerContainer: {
      flex: 1,

      marginBottom: 50,
    },
    scanSection: {
      alignItems: 'center',
      marginTop: 10,
      marginBottom: 20,
    },
    scanQRButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 153, 0, 0.1)',
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 25,
      borderWidth: 1,
      borderColor: '#ff9900',
    },
    scanQRButtonHover: {
      backgroundColor: '#23272a', 
      transform: [{ scale: 1.05 }], 
      borderColor: '#ffa726', 
      borderWidth: 2,
      shadowColor: '#ffa726',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.6, 
      shadowRadius: 10,
      elevation: 12,
      opacity: 0.95, 
    },
    
    scanQRText: {
      fontSize: 16,
      color: '#ff9900',
      fontWeight: 'bold',
      marginLeft: 10,
    },
    cameraContainer: {
      flex: 1,
      padding: 20,
      marginVertical: 20,
      borderRadius: 20,
      overflow: 'hidden',
    },
    camera: {
      height: '300',
      width: '100%',
    },
    exitCamera: {
      backgroundColor: '#676a74',
      padding: 15,
      borderRadius: 12,
      alignItems: 'center',
      marginTop: 10,
    },
    exitCameraText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: 'bold',
    },
    goalName: {
      color: '#FFFFFF',
      fontSize: 24,
      fontWeight: 'bold',
    },
    goalDetails: {
      color: '#FFFFFF',
      fontSize: 28,
      fontWeight: 'bold',
      lineHeight: 28,
    },
    recentGoals: {
      color: '#363636',
      paddingLeft: 20,
      marginTop: 20,
    },
    recentGoalsTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#2C3E50',
      marginBottom: 20,
    },
    goalsContainer: {
      flexDirection: 'row',

      paddingBottom: 20,
    },
    goalBox: {
      width: width * 0.45,
      marginRight: 15,
      padding: 15,
      height: '180',
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 3},
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 5,
    },
    chartContainer: {
      marginTop: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bmiContainer: {
      marginTop: 10,
      width: '100%',
      alignItems: 'center',
    },
    bmiLabel: {
      color: '#FFFFFF',
      fontSize: 12,
      marginBottom: 5,
    },
    bmiProgressBar: {
      width: '100%',
      height: 10,
      backgroundColor: 'rgba(255,255,255,0.3)',
      borderRadius: 5,
      overflow: 'hidden',
    },
    bmiProgress: {
      height: '100%',
      backgroundColor: '#FFFFFF',
      borderRadius: 5,
    },
    subscription: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
      backgroundColor: '#f7f7f7',
    },
    box: {
      width: '100%',
      padding: 20,
      borderRadius: 15,
      backgroundColor: '#ffffff',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 6,
    },
    titleContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
    },
    title: {
      fontSize: 22,
      fontWeight: 'bold',
      color: '#333',
      marginLeft: 10,
    },
    detailsContainer: {
      marginBottom: 20,
    },
    detailRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 15,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
    },
    label: {
      fontSize: 16,
      color: '#555',
    },
    valueContainer: {
      alignItems: 'flex-end',
    },
    value: {
      fontSize: 18,
      color: '#333',
      fontWeight: 'bold',
    },
    valuePKR: {
      fontSize: 14,
      color: '#777',
      marginTop: 3,
    },
    dateText: {
      fontSize: 14,
      color: '#777',
      marginTop: 3,
    },
    buttonContainer: {
      alignItems: 'center',
      marginTop: 10,
    },
    viewBillButton: {
      flexDirection: 'row',
      width: 200,
      paddingVertical: 12,
      backgroundColor: '#ff9900',
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    viewBillText: {
      fontSize: 16,
      color: '#ffffff',
      marginLeft: 10,
      fontWeight: '600',
    },
    successMessageContainer: {
      backgroundColor: '#222', 
      padding: 15,
      borderRadius: 8,
      marginTop: 20,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#FFFFFF', 
    },

    successMessageLine1: {
      color: '#fff', 
      fontSize: 18, 
      fontWeight: 'bold',
      textAlign: 'center',
      marginBottom: 5,
    },

    successMessageLine2: {
      color: 'green',
      fontSize: 16,
      textAlign: 'center',
      fontWeight: '500',
    },
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
      width: '80%',
      backgroundColor: 'white',
      borderRadius: 10,
      padding: 20,
      alignItems: 'center',
    },
    successMessage: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#4caf50',
      marginBottom: 10,
    },
    timestamp: {
      fontSize: 16,
      color: '#333',
      marginBottom: 20,
    },
    closeButton: {
      backgroundColor: '#4caf50',
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 5,
    },
    closeButtonText: {
      color: '#ffffff',
      fontSize: 16,
    },
  });

  export default styles;